# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-09 14:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, validators=[django.core.validators.RegexValidator(code='invalid_score', message='Score must in steps of 0.5', regex='^\\d\\.{0,5}$'), django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('userID', models.PositiveIntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movie.Movie')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='datasetrating',
            unique_together=set([('movie', 'userID')]),
        ),
    ]
