# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20170709_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together=set([('name', 'year')]),
        ),
    ]
