# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20170710_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbID',
            field=models.CharField(max_length=10),
        ),
    ]
