# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20170710_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='recommendations',
            field=models.ManyToManyField(blank=True, related_name='_movie_recommendations_+', to='movie.Movie'),
        ),
    ]
