# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-16 15:25
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='mean_rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=8, verbose_name='Popularity'),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='recommendations',
        ),
        migrations.AddField(
            model_name='movie',
            name='recommendations',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
