# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-16 19:16
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20170716_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mean_rating',
            field=models.DecimalField(decimal_places=7, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Average Rating'),
        ),
    ]
